### ISSUE TITLE
Please, for the love of all that is good, refactor the Odyssey Console Communication arduino script

### ISSUE THREAD

**Issue by PatHealy** [Vibrant-Media-Lab/OdysseyNowHAL#23]
The Console interface script is real ugly and hard to understand. It will probably work fine (though, I think the json isn't actually being outputted properly, so that should probably be fixed) but I know I have no idea how most of it works, from a brief glance. No one blame this on me!

**Comment by wenoptics** [comment]
Solve [fa7c5b](https://github.com/Vibrant-Media-Lab/OdysseyNowHAL/commit/fa7c5be205999a6f12b50e4388922e62913c4ebf). 

Will close after merge.
